import { unsplash } from '../utils/image';

export const DESTINATION_CATEGORIES = [
  'All',
  'Mountains',
  'Cities',
  'Wine Country',
  'Coast',
  'Ancient',
];

export const DESTINATIONS = [
  {
    id: 'kazbegi',
    name: 'Kazbegi',
    region: 'Mtskheta-Mtianeti',
    category: 'Mountains',
    tagline: 'Where a lonely church meets a 5,000m giant',
    image: unsplash('1589308078059-be1415eab4c3'),
    rating: 4.9,
    reviews: 812,
    featured: true,
  },
  {
    id: 'tbilisi',
    name: 'Tbilisi',
    region: 'Capital',
    category: 'Cities',
    tagline: 'Sulphur baths, balconies and a restless creative soul',
    image: unsplash('1565008447742-97f6f38c985c'),
    rating: 4.8,
    reviews: 1540,
    featured: true,
  },
  {
    id: 'kakheti',
    name: 'Kakheti',
    region: 'Wine Country',
    category: 'Wine Country',
    tagline: 'The cradle of wine, aged 8,000 years in clay',
    image: unsplash('1506377247377-2a5b3b417ebb'),
    rating: 4.9,
    reviews: 640,
    featured: true,
  },
  {
    id: 'svaneti',
    name: 'Svaneti',
    region: 'Samegrelo–Upper Svaneti',
    category: 'Mountains',
    tagline: 'Medieval stone towers beneath eternal snow',
    image: unsplash('1508739773434-c26b3d09e071'),
    rating: 5.0,
    reviews: 498,
    featured: true,
  },
  {
    id: 'batumi',
    name: 'Batumi',
    region: 'Adjara',
    category: 'Coast',
    tagline: 'Black Sea nights and subtropical boulevards',
    image: unsplash('1533105079780-92b9be482077'),
    rating: 4.6,
    reviews: 910,
  },
  {
    id: 'mtskheta',
    name: 'Mtskheta',
    region: 'Mtskheta-Mtianeti',
    category: 'Ancient',
    tagline: 'The holy city where two rivers become one',
    image: unsplash('1602343168117-bb8ffe3e2e9f'),
    rating: 4.7,
    reviews: 425,
  },
  {
    id: 'gudauri',
    name: 'Gudauri',
    region: 'Mtskheta-Mtianeti',
    category: 'Mountains',
    tagline: 'Powder ridgelines and paraglider skies',
    image: unsplash('1551524559-8af4e6624178'),
    rating: 4.8,
    reviews: 356,
  },
  {
    id: 'vardzia',
    name: 'Vardzia',
    region: 'Samtskhe-Javakheti',
    category: 'Ancient',
    tagline: 'A whole city carved into the cliff face',
    image: unsplash('1615887509046-3f0f1b3b3d3e'),
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 'sighnaghi',
    name: 'Sighnaghi',
    region: 'Kakheti',
    category: 'Wine Country',
    tagline: 'The city of love above the Alazani Valley',
    image: unsplash('1571104508999-893933ded431'),
    rating: 4.8,
    reviews: 512,
  },
];
