import { unsplash } from '../utils/image';

/** Options the admin can pick from when editing a hotel. */
export const HOTEL_CITIES = [
  'Tbilisi',
  'Batumi',
  'Kazbegi',
  'Kutaisi',
  'Mestia',
  'Sighnaghi',
  'Gudauri',
  'Borjomi',
];

export const HOTEL_TYPES = [
  'Luxury Hotel',
  'Boutique',
  'Resort',
  'Guesthouse',
  'Ski Lodge',
  'Wine Estate',
  'Spa Retreat',
];

export const HOTEL_STATUSES = ['published', 'draft', 'archived'];

/** id → { label, icon } where icon is a lucide component name handled by AmenityIcon. */
export const AMENITIES = [
  { id: 'wifi', label: 'Free WiFi', icon: 'wifi' },
  { id: 'pool', label: 'Swimming Pool', icon: 'pool' },
  { id: 'spa', label: 'Spa & Wellness', icon: 'spa' },
  { id: 'restaurant', label: 'Restaurant', icon: 'restaurant' },
  { id: 'bar', label: 'Bar / Lounge', icon: 'bar' },
  { id: 'parking', label: 'Free Parking', icon: 'parking' },
  { id: 'gym', label: 'Fitness Center', icon: 'gym' },
  { id: 'shuttle', label: 'Airport Shuttle', icon: 'shuttle' },
  { id: 'pet', label: 'Pet Friendly', icon: 'pet' },
  { id: 'view', label: 'Mountain View', icon: 'view' },
  { id: 'wine', label: 'Wine Cellar', icon: 'wine' },
  { id: 'fireplace', label: 'Fireplace', icon: 'fireplace' },
  { id: 'concierge', label: '24/7 Concierge', icon: 'concierge' },
  { id: 'ski', label: 'Ski-in / Ski-out', icon: 'ski' },
  { id: 'breakfast', label: 'Breakfast Included', icon: 'breakfast' },
];

/** Blank hotel used when creating a new record. */
export const EMPTY_HOTEL = {
  name: '',
  type: 'Boutique',
  city: 'Tbilisi',
  address: '',
  tagline: '',
  description: '',
  stars: 5,
  pricePerNight: 120,
  currency: 'USD',
  rating: 4.8,
  reviews: 0,
  roomsCount: 20,
  rooms: [], // room-rate table [{ category, prices }] — synced to the sheet tab
  notes: [], // free-text notes from the sheet tab
  images: [],
  amenities: ['wifi', 'breakfast'],
  status: 'draft',
  featured: false,
  available: true,
  checkIn: '14:00',
  checkOut: '12:00',
};

export const HOTELS_SEED = [
  {
    id: 'h-rooms-tbilisi',
    name: 'Rooms Hotel Tbilisi',
    type: 'Boutique',
    city: 'Tbilisi',
    address: '14 Merab Kostava St, Tbilisi',
    tagline: 'Industrial-chic design in the heart of the capital',
    description:
      'A design-led boutique hotel set in a restored publishing house, blending vintage leather, brass and greenery with a buzzing lobby bar.',
    stars: 5,
    pricePerNight: 210,
    currency: 'USD',
    rating: 4.9,
    reviews: 1284,
    rooms: 125,
    images: [unsplash('1566073771259-6a8506099945'), unsplash('1520250497591-112f2f40a3f4')],
    amenities: ['wifi', 'restaurant', 'bar', 'spa', 'gym', 'concierge', 'breakfast'],
    status: 'published',
    featured: true,
    available: true,
    checkIn: '14:00',
    checkOut: '12:00',
  },
  {
    id: 'h-kazbegi',
    name: 'Rooms Hotel Kazbegi',
    type: 'Resort',
    city: 'Kazbegi',
    address: 'Stepantsminda, Kazbegi',
    tagline: 'Floor-to-ceiling views of Mount Kazbek',
    description:
      'Perched above Stepantsminda, this alpine retreat frames the Gergeti Trinity Church and glacier peaks from an infinity pool and vast panoramic lounges.',
    stars: 5,
    pricePerNight: 245,
    currency: 'USD',
    rating: 4.8,
    reviews: 940,
    rooms: 156,
    images: [unsplash('1542314831-068cd1dbfeeb'), unsplash('1571896349842-33c89424de2d')],
    amenities: ['wifi', 'pool', 'spa', 'restaurant', 'bar', 'view', 'fireplace', 'parking'],
    status: 'published',
    featured: true,
    available: true,
    checkIn: '15:00',
    checkOut: '12:00',
  },
  {
    id: 'h-gudauri-lodge',
    name: 'Gudauri Alpine Lodge',
    type: 'Ski Lodge',
    city: 'Gudauri',
    address: 'New Gudauri, Kazbegi Municipality',
    tagline: 'Ski-in, ski-out on the Great Caucasus',
    description:
      'A warm timber-and-stone lodge steps from the gondola, with a wood-fired sauna, boot room and a south-facing terrace over the powder bowls.',
    stars: 4,
    pricePerNight: 160,
    currency: 'USD',
    rating: 4.7,
    reviews: 512,
    rooms: 48,
    images: [unsplash('1520250497591-112f2f40a3f4'), unsplash('1618773928121-c32242e63f39')],
    amenities: ['wifi', 'ski', 'spa', 'restaurant', 'bar', 'fireplace', 'view'],
    status: 'published',
    featured: false,
    available: true,
    checkIn: '15:00',
    checkOut: '11:00',
  },
  {
    id: 'h-batumi-sea',
    name: 'Le Méridien Batumi',
    type: 'Luxury Hotel',
    city: 'Batumi',
    address: 'Ninoshvili St, Batumi Seafront',
    tagline: 'Black Sea glamour on the boulevard',
    description:
      'A landmark seafront tower with a rooftop pool, casino-era sparkle and sunset-facing suites over the Batumi promenade.',
    stars: 5,
    pricePerNight: 190,
    currency: 'USD',
    rating: 4.6,
    reviews: 1105,
    rooms: 282,
    images: [unsplash('1582719508461-905c673771fd'), unsplash('1445019980597-93fa8acb246c')],
    amenities: ['wifi', 'pool', 'spa', 'restaurant', 'bar', 'gym', 'concierge', 'parking'],
    status: 'published',
    featured: true,
    available: true,
    checkIn: '14:00',
    checkOut: '12:00',
  },
  {
    id: 'h-sighnaghi-estate',
    name: 'Château Sighnaghi Wine Estate',
    type: 'Wine Estate',
    city: 'Sighnaghi',
    address: 'Above the Alazani Valley, Sighnaghi',
    tagline: 'Sleep among the vines of Kakheti',
    description:
      'A boutique winery-hotel with qvevri cellars, private tastings and a terrace looking across the golden Alazani Valley to the Caucasus.',
    stars: 4,
    pricePerNight: 175,
    currency: 'USD',
    rating: 4.9,
    reviews: 388,
    rooms: 22,
    images: [unsplash('1611892440504-42a792e24d32'), unsplash('1590490360182-c33d57733427')],
    amenities: ['wifi', 'wine', 'restaurant', 'view', 'fireplace', 'breakfast', 'parking'],
    status: 'draft',
    featured: false,
    available: true,
    checkIn: '14:00',
    checkOut: '11:00',
  },
  {
    id: 'h-mestia-tower',
    name: 'Mestia Tower Guesthouse',
    type: 'Guesthouse',
    city: 'Mestia',
    address: 'Old Town, Mestia, Svaneti',
    tagline: 'A restored Svan tower with modern comfort',
    description:
      'A characterful family-run guesthouse built into a medieval Svan defence tower, with hearty home cooking and glacier views from every window.',
    stars: 3,
    pricePerNight: 85,
    currency: 'USD',
    rating: 4.8,
    reviews: 274,
    rooms: 9,
    images: [unsplash('1590490360182-c33d57733427')],
    amenities: ['wifi', 'breakfast', 'view', 'fireplace', 'pet'],
    status: 'published',
    featured: false,
    available: false,
    checkIn: '13:00',
    checkOut: '11:00',
  },
];
