import { unsplash } from '../utils/image';

export const TOUR_FILTERS = ['All', 'Adventure', 'Culture', 'Wine & Food', 'Winter'];

export const TOURS = [
  {
    id: 'caucasus-crossing',
    title: 'Great Caucasus Crossing',
    category: 'Adventure',
    image: unsplash('1464822759023-fed622ff2c3b'),
    days: 8,
    difficulty: 'Challenging',
    season: 'Jun – Sep',
    groupSize: '4–10',
    price: 1490,
    rating: 4.9,
    reviews: 214,
    summary:
      'Trek from Mestia to Ushguli through Svaneti’s tower villages, alpine passes and glacier valleys.',
    highlights: ['Mestia to Ushguli trek', 'Glacier viewpoints', 'Stay in stone towers'],
    featured: true,
  },
  {
    id: 'wine-soul-kakheti',
    title: 'The Soul of Georgian Wine',
    category: 'Wine & Food',
    image: unsplash('1510812431401-41d2bd2722f3'),
    days: 4,
    difficulty: 'Easy',
    season: 'All year',
    groupSize: '2–8',
    price: 720,
    rating: 5.0,
    reviews: 168,
    summary:
      'Qvevri cellars, supra feasts and hilltop monasteries across the golden Alazani Valley.',
    highlights: ['8,000-year qvevri wine', 'Private supra dinner', 'Sighnaghi old town'],
    featured: true,
  },
  {
    id: 'tbilisi-mtskheta-city',
    title: 'Tbilisi & Ancient Mtskheta',
    category: 'Culture',
    image: unsplash('1565008447742-97f6f38c985c'),
    days: 3,
    difficulty: 'Easy',
    season: 'All year',
    groupSize: '2–12',
    price: 480,
    rating: 4.8,
    reviews: 301,
    summary:
      'Old-town balconies, sulphur baths and the UNESCO churches where Georgia was baptised.',
    highlights: ['Abanotubani baths', 'Jvari & Svetitskhoveli', 'Rooftop wine bars'],
    featured: true,
  },
  {
    id: 'gudauri-freeride',
    title: 'Gudauri Freeride Week',
    category: 'Winter',
    image: unsplash('1551524559-8af4e6624178'),
    days: 6,
    difficulty: 'Moderate',
    season: 'Dec – Mar',
    groupSize: '4–8',
    price: 1180,
    rating: 4.7,
    reviews: 96,
    summary: 'Off-piste powder, cat-skiing and heli lines on the flanks of the Great Caucasus.',
    highlights: ['Guided off-piste', 'Cat-ski sessions', 'Mountain chalet stay'],
  },
  {
    id: 'kazbegi-express',
    title: 'Kazbegi Mountain Express',
    category: 'Adventure',
    image: unsplash('1589308078059-be1415eab4c3'),
    days: 2,
    difficulty: 'Moderate',
    season: 'Apr – Nov',
    groupSize: '2–14',
    price: 320,
    rating: 4.9,
    reviews: 388,
    summary:
      'The Georgian Military Highway to Gergeti Trinity Church beneath the great Mount Kazbek.',
    highlights: ['Ananuri fortress', 'Gergeti Trinity hike', 'Panorama viewpoints'],
  },
  {
    id: 'black-sea-adjara',
    title: 'Black Sea & Green Adjara',
    category: 'Culture',
    image: unsplash('1533105079780-92b9be482077'),
    days: 5,
    difficulty: 'Easy',
    season: 'May – Oct',
    groupSize: '2–10',
    price: 640,
    rating: 4.6,
    reviews: 142,
    summary: 'Batumi’s seafront, tea terraces, waterfalls and arched stone bridges of Adjara.',
    highlights: ['Botanical garden', 'Mtirala rainforest', 'Seaside boulevard'],
  },
];

export const EXPERIENCES = [
  {
    id: 'wine',
    title: 'Wine & Supra',
    icon: 'wine',
    image: unsplash('1524594152303-9fd13543fe6e'),
    text: 'Toast with a tamada at a traditional feast and taste amber wine from clay qvevri.',
  },
  {
    id: 'mountains',
    title: 'Mountain Adventure',
    icon: 'mountain',
    image: unsplash('1454496522488-7a8e488e8606'),
    text: 'Hike, paraglide and ride horseback across the ridgelines of the Great Caucasus.',
  },
  {
    id: 'culture',
    title: 'Culture & History',
    icon: 'landmark',
    image: unsplash('1602343168117-bb8ffe3e2e9f'),
    text: 'Walk through cave cities, cliff monasteries and cobbled old towns older than memory.',
  },
  {
    id: 'cuisine',
    title: 'Georgian Cuisine',
    icon: 'utensils',
    image: unsplash('1504674900247-0877df9cc836'),
    text: 'From khinkali to khachapuri — a table where every dish tells a story of the region.',
  },
  {
    id: 'nature',
    title: 'Wild Nature',
    icon: 'trees',
    image: unsplash('1441974231531-c6227db76b6e'),
    text: 'Waterfalls, canyons, alpine lakes and subtropical forests within a single small country.',
  },
  {
    id: 'winter',
    title: 'Winter & Ski',
    icon: 'snowflake',
    image: unsplash('1551524559-8af4e6624178'),
    text: 'Fresh powder and empty slopes at Gudauri, Bakuriani and hidden freeride bowls.',
  },
];
